server:
  port: 8888

spring:
  application:
    name: config-service
#  profiles:
#    active: native
  cloud:
    config:
      server:
#        native:
#          search-locations: file://${user.home}/Desktop/study/msa/native-file-repo
        git:
          uri: https://github.com/malvr00/MSA-Config-Server.git
#          private 일 경우
#          username: ###
#          password: ###
#          uri: file:///Users/yong/Desktop/study/msa-configserver