server:
  port: 9001

spring:
  application:
    name: user-service

eureka:
  client:
#   registry? ?? ?? ??
    register-with-eureka: true
#    true -> EUREKA ????? ?????? ??? ????? ??? ??? ??
    fetch-registry: true
#   eureka server ?? ?? ( ?? ?? )
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

