server:
  port: 0

spring:
  application:
    name: user-service

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instans_id:${random.value}}
  client:
#   registry? ?? ?? ??
    register-with-eureka: true
#    true -> EUREKA ????? ?????? ??? ????? ??? ??? ??
    fetch-registry: true
#   eureka server ?? ?? ( ?? ?? )
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

