server:
  port: 8761

spring:
  application:
    name: discorveryservice
  cloud:
    config:
      uri: http://127.0.0.1:8888
      name: ecommerce
# Service Discorvery? ?? ??? ?? ?? ???? false? ??? ?.
# ???? ? ?? ??? ?? ??? ??? ??? ?? ?? ?? ??.
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
