server:
  port: 0

spring:
  application:
    name: user-servier
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

eureka:
  client:
# Service Discorvery? ??(register-with-eureka, fetch-registry ?? ?? ?? ??? ?? ?? true? ??????.).
    register-with-eureka: true
    fetch-registry: true
# eureka end-point(http://127.0.0.1:8761/eureka)? ???? ??? ??
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

greeting:
  message:  Welcome to the Simple E-commerce
