server:
  port: 0

spring:
  application:
    name: user-servier

eureka:
  client:
# Service Discorvery? ??(register-with-eureka, fetch-registry ?? ?? ?? ??? ?? ?? true? ??????.).
    register-with-eureka: true
    fetch-registry: true
# eureka end-point(http://127.0.0.1:8761/eureka)? ???? ??? ??
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
